image: thyrlian/android-sdk:latest

variables:
  ANDROID_SDK: "cache/adk"
  GRADLEW: "./gradlew --gradle-user-home cache/gradle"

before_script:
  - echo "sdk.dir=${ANDROID_SDK}" > local.properties
  - wget https://raw.githubusercontent.com/thyrlian/AndroidSDK/master/android-sdk/license_accepter.sh
  - chmod 755 license_accepter.sh
  - ./license_accepter.sh $ANDROID_SDK
  - chmod +x ./gradlew



cache:
  key: ${CI_PROJECT_ID}
  paths:
    - cache


stages:
  - build
  - test


deploy:
  stage: build
  only:
    - tags
  script:
    - $GRADLEW :databinding-base:bintrayUpload
  artifacts:
    paths:
      - databinding-base/build/outputs/

assemble:
  stage: build
  only:
    - master
  script:
    - $GRADLEW :app:assembleDebug
  artifacts:
    paths:
      - databinding-base/build/outputs/



