image: thyrlian/android-sdk:latest

before_script:
  - sdkmanager "build-tools;26.0.3" "platforms;android-26" "tools"
  - chmod +x ./gradlew

stages:
  - build
  - test


deploy:
  stage: build
  only:
    - tags
  script:
    - ./gradlew :databinding-base:bintrayUpload
  artifacts:
    paths:
    - app/build/outputs/apk



unitTests:
  stage: test
  only:
    - release
    - master
  script:
    - ./gradlew test

